[tool.poetry]
name = "superlists"
version = "0.1.0"
description = "project-tdd"
authors = ["Edson"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
